package com.github.avrokotlin.avro4k

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.shouldBe
import io.kotest.matchers.types.shouldBeSameInstanceAs
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.serializer
import org.apache.avro.AvroRuntimeException
import org.apache.avro.Schema
import org.apache.avro.util.internal.Accessor
import java.io.File
import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.util.UUID
import kotlin.jvm.JvmInline

/**
 * Guards the conversions between [AvroSchema] and Apache's [Schema] over every schema of the other modules' test suites,
 * plus the schemas avro4k generates for a representative set of classes.
 */
class AvroSchemaApacheInteropTest : FunSpec({
    val rootDir = File(System.getProperty("avro4k.rootDir") ?: error("Missing avro4k.rootDir system property"))

    val schemaFiles =
        listOf("core/src/jvmTest/resources", "kotlin-generator/src/test/resources")
            .map { rootDir.resolve(it) }
            .flatMap { dir ->
                dir.walkTopDown().filter { it.isFile && (it.extension == "avsc" || it.extension == "json") }.toList()
            }
            .sorted()

    test("finds the test suites' schema files") {
        // guards against a moved resources directory silently emptying the round-trip coverage
        (schemaFiles.size > 90) shouldBe true
    }

    // Files are parsed per directory, sharing the known types, as some of them reference types defined in other files
    val schemasFromFiles: List<Pair<String, Pair<Schema, AvroSchema>>> =
        schemaFiles.groupBy { it.parentFile }.flatMap { (dir, files) -> parseDirectory(dir, files, rootDir) }

    test("parses every schema file") {
        schemasFromFiles.size shouldBe schemaFiles.size - UNPARSEABLE_FILES.size
    }

    schemasFromFiles.forEach { (name, schemas) ->
        val (apacheSchema, parsedAvro4kSchema) = schemas
        context(name) {
            test("apache -> avro4k -> apache") {
                val roundTripped = apacheSchema.toAvro4k().toApacheSchema()
                if (name in DEFAULTS_COERCED_BY_APACHE) {
                    roundTripped shouldBe apacheSchema.withNormalizedDefaults()
                } else {
                    roundTripped shouldBe apacheSchema
                }
            }
            test("apache -> avro4k -> apache -> avro4k is stable") {
                val avro4k = apacheSchema.toAvro4k()
                avro4k.toApacheSchema().toAvro4k() shouldBe avro4k
            }
            test("avro4k parsed from json -> apache -> avro4k") {
                if (name in DEFAULTS_COERCED_BY_APACHE) {
                    parsedAvro4kSchema.toApacheSchema().toAvro4k() shouldBe apacheSchema.toAvro4k()
                } else {
                    parsedAvro4kSchema.toApacheSchema().toAvro4k() shouldBe parsedAvro4kSchema
                }
            }
            test("avro4k's json parser and the apache conversion agree") {
                if (name !in DEFAULTS_COERCED_BY_APACHE) {
                    apacheSchema.toAvro4k() shouldBe parsedAvro4kSchema
                }
            }
        }
    }

    context("schemas generated by avro4k") {
        GENERATED_SCHEMAS.forEach { serializer ->
            test(serializer.descriptor.serialName) {
                val apacheSchema = Avro.schema(serializer)
                val avro4k = apacheSchema.toAvro4k()
                // Same json, but compared with a parsed schema: Apache compares defaults by json node type, and core builds some
                // defaults with a different node type than the parser (see "core's int defaults are big integer json nodes")
                avro4k.toApacheSchema().toString() shouldBe apacheSchema.toString()
                avro4k.toApacheSchema() shouldBe Schema.Parser().parse(apacheSchema.toString())
                avro4k.toApacheSchema().toAvro4k() shouldBe avro4k
                AvroSchema.fromJsonString(apacheSchema.toString()) shouldBe avro4k
            }
        }
    }

    test("core's int defaults are big integer json nodes") {
        // Why the generated schemas are compared to their parsed json: Apache's field equality compares the default json nodes, including their type
        val field = Avro.schema(Everything.serializer()).getField("withDefault")
        Accessor.defaultValue(field).isBigInteger shouldBe true
        field.defaultVal() shouldBe null
        (Avro.schema(Everything.serializer()).toAvro4k() as AvroSchema.RecordSchema).getFieldByName("withDefault").defaultValue shouldBe JsonPrimitive(42)
    }

    test("recursive records keep their identity") {
        val schema = Avro.schema(Node.serializer()).toAvro4k() as AvroSchema.RecordSchema
        val next = schema.getFieldByName("next").schema as AvroSchema.UnionSchema
        next.types[1] shouldBeSameInstanceAs schema
        schema.toApacheSchema().toAvro4k() shouldBe schema
    }

    test("field order is kept as a field prop") {
        val json = """{"type":"record","name":"R","fields":[{"name":"a","type":"int","order":"descending"},{"name":"b","type":"int","order":"ignore"}]}"""
        val apacheSchema = Schema.Parser().parse(json)
        val avro4k = apacheSchema.toAvro4k() as AvroSchema.RecordSchema
        avro4k.fields.map { it.props["order"]?.toString() } shouldBe listOf("\"descending\"", "\"ignore\"")
        avro4k shouldBe AvroSchema.fromJsonString(json)
        avro4k.toApacheSchema() shouldBe apacheSchema
    }

    test("the known exceptions are still exceptions") {
        // if one of those starts to round-trip, remove it from the list
        schemasFromFiles.filter { (name, schemas) -> name in DEFAULTS_COERCED_BY_APACHE && schemas.first.toAvro4k().toApacheSchema() == schemas.first }
            .map { it.first }
            .shouldBeEmpty()
    }
}) {
    private companion object {
        /**
         * Schemas whose field defaults Apache Avro coerces to the field's type ([Schema.Field.defaultVal]), which [toAvro4k] relies on,
         * so the textual default changes (e.g. `36` becomes `36.0` for a float field), and Apache's json node equality is textual.
         */
        val DEFAULTS_COERCED_BY_APACHE =
            setOf(
                "kotlin-generator/src/test/resources/record-as-default.avsc"
            )

        /** Invalid schemas on purpose */
        val UNPARSEABLE_FILES =
            setOf(
                // references an undefined type, to test kotlin-generator's failure
                "kotlin-generator/src/test/resources/types-across-multiple-files-fail/type-record-without-namespace.avsc"
            )

        val GENERATED_SCHEMAS: List<KSerializer<*>> =
            listOf(
                serializer<Everything>(),
                serializer<Node>(),
                serializer<Tree>(),
                serializer<Shape>(),
                serializer<Suit>(),
                serializer<Wrapper>(),
                serializer<List<Map<String, Everything?>>>(),
                serializer<Map<String, Shape?>>(),
                serializer<String?>(),
                serializer<Int>()
            )

        /**
         * Parses each file on its own. The files that reference types defined in other files of the same directory
         * are then parsed with all the directory's files, sharing the known types.
         */
        fun parseDirectory(
            dir: File,
            files: List<File>,
            rootDir: File,
        ): List<Pair<String, Pair<Schema, AvroSchema>>> {
            val results = mutableListOf<Pair<String, Pair<Schema, AvroSchema>>>()
            val needingOtherFiles =
                files.filter { file ->
                    if (file.relativeTo(rootDir).path in UNPARSEABLE_FILES) return@filter false
                    val apacheSchema =
                        try {
                            Schema.Parser().parse(file)
                        } catch (_: AvroRuntimeException) {
                            return@filter true
                        }
                    results += file.relativeTo(rootDir).path to (apacheSchema to AvroSchema.fromJsonString(file.readText()))
                    false
                }
            if (needingOtherFiles.isEmpty()) return results

            val parser = Schema.Parser()
            val knownAvro4kTypes = mutableMapOf<String, AvroSchema>()
            val remaining = files.filter { it.relativeTo(rootDir).path !in UNPARSEABLE_FILES }.toMutableList()
            // retry until no progress, as files may reference types of files parsed later
            while (remaining.isNotEmpty()) {
                val parsed =
                    remaining.filter { file ->
                        val apacheSchema =
                            try {
                                parser.parse(file)
                            } catch (_: AvroRuntimeException) {
                                return@filter false
                            }
                        val avro4kSchema = AvroSchema.fromJsonString(file.readText(), knownAvro4kTypes)
                        if (file in needingOtherFiles) {
                            results += file.relativeTo(rootDir).path to (apacheSchema to avro4kSchema)
                        }
                        true
                    }
                if (parsed.isEmpty()) break
                remaining -= parsed.toSet()
            }
            check(remaining.isEmpty()) { "Unparseable schema files in $dir: ${remaining.map { it.relativeTo(rootDir).path }}" }
            return results
        }

        /** Re-parses the schema from its json, after going through avro4k, to get the coerced defaults as json nodes */
        fun Schema.withNormalizedDefaults(): Schema = Schema.Parser().parse(toAvro4k().toApacheSchema().toString())
    }
}

@Serializable
@SerialName("interop.Node")
private data class Node(
    val value: Int,
    val next: Node? = null,
)

@Serializable
@SerialName("interop.Tree")
private data class Tree(
    val children: List<Tree>,
    val byName: Map<String, Tree>,
)

@Serializable
@SerialName("interop.Suit")
private enum class Suit {
    HEARTS,

    @AvroEnumDefault
    SPADES,
}

@Serializable
@SerialName("interop.Shape")
private sealed interface Shape {
    @Serializable
    @SerialName("interop.Circle")
    data class Circle(val radius: Double) : Shape

    @Serializable
    @SerialName("interop.other.Square")
    data class Square(val side: Double) : Shape

    @Serializable
    @SerialName("interop.Empty")
    data object Empty : Shape
}

@JvmInline
@Serializable
private value class Wrapper(val value: String)

@Serializable
@SerialName("interop.Everything")
@AvroDoc("A record with every kind of schema")
@AvroAlias("interop.OldEverything", "OtherName")
@AvroProp("custom", "value")
@AvroProp("jsonProp", """{"a":[1,2,{"b":null}]}""")
private data class Everything(
    val int: Int,
    val long: Long,
    val float: Float,
    val double: Double,
    val boolean: Boolean,
    val string: String,
    val bytes: ByteArray,
    @AvroFixed(8) val fixed: ByteArray,
    @AvroDecimal(scale = 2, precision = 8) @Contextual val decimal: BigDecimal,
    @Contextual val uuid: UUID,
    @Contextual val date: LocalDate,
    @Contextual val time: LocalTime,
    @Contextual val dateTime: LocalDateTime,
    @Contextual val instant: Instant,
    val nullable: String?,
    @AvroDefault("42") val withDefault: Int,
    @AvroDefault("4.5") val floatWithDefault: Float,
    @AvroDefault("[1, 2]") val listWithDefault: List<Long>,
    @AvroDefault("HEARTS") val enumWithDefault: Suit,
    @AvroDefault("null") val nullableWithDefault: Node?,
    val list: List<Node>,
    val set: Set<Int>,
    val map: Map<String, Node?>,
    val nestedCollections: Map<String, List<Map<String, Int?>>>,
    val suit: Suit,
    val shape: Shape,
    val nullableShape: Shape?,
    val tree: Tree,
    @AvroAlias("oldName", "otherOldName") @AvroDoc("a field doc") @AvroProp("fieldProp", "1") val aliased: String,
    val wrapper: Wrapper,
    @AvroStringable val stringable: Int,
)