package com.github.avrokotlin.avro4k

import com.github.avrokotlin.avro4k.internal.apacheConversionCacheSize
import com.github.avrokotlin.avro4k.internal.apacheToAvro4kUncached
import com.github.avrokotlin.avro4k.internal.avro4kToApacheUncached
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.ints.shouldBeGreaterThan
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.types.shouldBeSameInstanceAs
import io.kotest.matchers.types.shouldNotBeSameInstanceAs
import kotlinx.serialization.json.JsonPrimitive
import org.apache.avro.Schema
import java.io.File
import java.lang.ref.WeakReference
import java.util.IdentityHashMap
import java.util.concurrent.atomic.AtomicInteger

/**
 * The pairing of the cached conversions (M3-05's two-way seeding): for every node `s` of an Apache schema and the node `a`
 * at the same position of its conversion, `s.toAvro4k() === a` and `a.toApacheSchema() === s`, whichever side was
 * converted, and the pairs stay collectable.
 */
class AvroSchemaApacheIdentityTest : FunSpec({
    val rootDir = File(System.getProperty("avro4k.rootDir") ?: error("Missing avro4k.rootDir system property"))

    test("apache first: every node of the schema files is paired with the node at the same position") {
        val corpus = AvroSchemaApacheInteropTest.parseSchemaFiles(rootDir)
        (corpus.size > 90) shouldBe true
        var pairCount = 0
        corpus.forEach { (name, schemas) ->
            withClue(name) {
                val apache = schemas.first
                pairCount += shouldBePairedAtEveryNode(apache, apache.toAvro4k())
            }
        }
        pairCount shouldBeGreaterThan corpus.size
    }

    test("avro4k first: every node of the schema files is paired with the node at the same position") {
        val corpus = AvroSchemaApacheInteropTest.parseSchemaFiles(rootDir)
        corpus.forEach { (name, schemas) ->
            withClue(name) {
                val avro4k = schemas.second
                shouldBePairedAtEveryNode(avro4k.toApacheSchema(), avro4k)
            }
        }
    }

    test("schemas generated by avro4k are paired at every node, both ways") {
        AvroSchemaApacheInteropTest.GENERATED_SCHEMAS.forEach { serializer ->
            withClue(serializer.descriptor.serialName) {
                val apache = Avro.schema(serializer)
                shouldBePairedAtEveryNode(apache, apache.toAvro4k())
                val avro4k = AvroSchema.fromJsonString(apache.toString())
                shouldBePairedAtEveryNode(avro4k.toApacheSchema(), avro4k)
            }
        }
    }

    context("recursive records and shared named types") {
        test("apache first") {
            val apache = Schema.Parser().parse(recursiveJson("apacheFirst"))
            val avro4k = apache.toAvro4k() as AvroSchema.RecordSchema
            avro4k.shouldShareLikeTheRecursiveSchema()
            shouldBePairedAtEveryNode(apache, avro4k) shouldBe 9
        }
        test("avro4k first") {
            val avro4k = AvroSchema.fromJsonString(recursiveJson("avro4kFirst")) as AvroSchema.RecordSchema
            avro4k.shouldShareLikeTheRecursiveSchema()
            val apache = avro4k.toApacheSchema()
            apache.getField("left").schema() shouldBeSameInstanceAs apache.getField("right").schema()
            apache.getField("self").schema().types[1] shouldBeSameInstanceAs apache
            shouldBePairedAtEveryNode(apache, avro4k) shouldBe 9
        }
        test("apache: a sub-schema converted first is reused by the conversion of its root") {
            val apache = Schema.Parser().parse(recursiveJson("apacheSubFirst"))
            val leaf = apache.getField("left").schema()
            val leafAvro4k = leaf.toAvro4k()
            val avro4k = apache.toAvro4k() as AvroSchema.RecordSchema
            avro4k.getFieldByName("left").schema shouldBeSameInstanceAs leafAvro4k
            shouldBePairedAtEveryNode(apache, avro4k)
        }
        test("avro4k: a named sub-schema converted first keeps its partner, and its position in the root's conversion is paired on its own") {
            // Apache's parser copies the records it resolves, so the json route cannot reuse the sub-schema's apache node
            val avro4k = AvroSchema.fromJsonString(recursiveJson("avro4kSubFirst")) as AvroSchema.RecordSchema
            val leaf = avro4k.getFieldByName("left").schema
            val leafApache = leaf.toApacheSchema()
            val apache = avro4k.toApacheSchema()
            apache.getField("left").schema() shouldNotBeSameInstanceAs leafApache
            leaf.toApacheSchema() shouldBeSameInstanceAs leafApache
            pairsOf(apache, avro4k).forEach { (apacheNode, avro4kNode) ->
                apacheNode.toAvro4k().toApacheSchema() shouldBeSameInstanceAs apacheNode
                avro4kNode.toApacheSchema().toAvro4k() shouldBeSameInstanceAs avro4kNode
            }
        }
    }

    test("the uncached conversions neither read nor fill the caches") {
        val apache = Schema.Parser().parse(recursiveJson("uncached"))
        val avro4k = AvroSchema.fromJsonString(recursiveJson("uncached"))
        val sizeBefore = apacheConversionCacheSize()
        val fromApache = apacheToAvro4kUncached(apache)
        val fromAvro4k = avro4kToApacheUncached(avro4k)
        apacheConversionCacheSize() shouldBe sizeBefore

        // nothing was paired: the cached conversions do their own
        pairsOf(apache, fromApache).forEach { (apacheNode, converted) -> apacheNode.toAvro4k() shouldNotBeSameInstanceAs converted }
        pairsOf(apache, fromApache).forEach { (apacheNode, converted) -> converted.toApacheSchema() shouldNotBeSameInstanceAs apacheNode }
        pairsOf(fromAvro4k, avro4k).forEach { (converted, avro4kNode) -> avro4kNode.toApacheSchema() shouldNotBeSameInstanceAs converted }
        fromAvro4k.toAvro4k() shouldNotBeSameInstanceAs avro4k

        // and a pairing is not read: the uncached conversion of a paired schema is a new one
        apacheToAvro4kUncached(apache) shouldNotBeSameInstanceAs apache.toAvro4k()
        avro4kToApacheUncached(avro4k) shouldNotBeSameInstanceAs avro4k.toApacheSchema()
    }

    context("collectability: each pair has one strong link, from the converted node to its partner") {
        test("the converted apache schema keeps its avro4k partner alive") {
            val apache = Schema.Parser().parse(recursiveJson("apacheKeeps"))
            val avro4k = weakly { apache.toAvro4k() }
            churnCaches(3) shouldBe true
            avro4k.get() shouldNotBe null
            apache.toAvro4k() shouldBeSameInstanceAs avro4k.get()
        }
        test("the converted avro4k schema keeps its apache partner alive") {
            val avro4k = AvroSchema.fromJsonString(recursiveJson("avro4kKeeps"))
            val apache = weakly { avro4k.toApacheSchema() }
            churnCaches(3) shouldBe true
            apache.get() shouldNotBe null
            avro4k.toApacheSchema() shouldBeSameInstanceAs apache.get()
        }
        test("the avro4k partner does not keep the converted apache schema alive, and is paired again with a new one") {
            val (avro4k, apache) = avro4kOfForgottenApache("apacheForgotten")
            awaitCollected(apache) shouldBe true
            val newApache = avro4k.toApacheSchema()
            newApache.toString() shouldBe Schema.Parser().parse(recursiveJson("apacheForgotten")).toString()
            shouldBePairedAtEveryNode(newApache, avro4k)
        }
        test("the apache partner does not keep the converted avro4k schema alive, and is paired again with a new one") {
            val (apache, avro4k) = apacheOfForgottenAvro4k("avro4kForgotten")
            awaitCollected(avro4k) shouldBe true
            val newAvro4k = apache.toAvro4k()
            newAvro4k shouldBe AvroSchema.fromJsonString(recursiveJson("avro4kForgotten"))
            shouldBePairedAtEveryNode(apache, newAvro4k)
        }
        test("a pair made from apache is collectable once both schemas are unreachable") {
            awaitCollected(*forgottenPairFromApache("pairFromApache")) shouldBe true
        }
        test("a pair made from avro4k is collectable once both schemas are unreachable") {
            awaitCollected(*forgottenPairFromAvro4k("pairFromAvro4k")) shouldBe true
        }
    }
})

/**
 * Asserts that each node of [apache] and the node of [avro4k] at the same position are paired both ways, and that both trees
 * share their nodes alike (a node reached twice on one side is reached twice on the other). Returns the number of pairs.
 */
private fun shouldBePairedAtEveryNode(
    apache: Schema,
    avro4k: AvroSchema,
): Int {
    val pairs = pairsOf(apache, avro4k)
    pairs.forEach { (apacheNode, avro4kNode) ->
        withClue("${apacheNode.type} node $apacheNode") {
            apacheNode.toAvro4k() shouldBeSameInstanceAs avro4kNode
            avro4kNode.toApacheSchema() shouldBeSameInstanceAs apacheNode
        }
    }
    pairs.map { it.first }.distinctByIdentity() shouldHaveSize pairs.size
    pairs.map { it.second }.distinctByIdentity() shouldHaveSize pairs.size
    return pairs.size
}

/** The pairs of nodes at the same position of both trees, walked in parallel, each pair once (recursion included). */
internal fun pairsOf(
    apache: Schema,
    avro4k: AvroSchema,
): List<Pair<Schema, AvroSchema>> {
    val visited = IdentityHashMap<Schema, MutableList<AvroSchema>>()
    val pairs = mutableListOf<Pair<Schema, AvroSchema>>()

    fun walk(
        apacheNode: Schema,
        avro4kNode: AvroSchema,
    ) {
        val seenWith = visited.getOrPut(apacheNode) { mutableListOf() }
        if (seenWith.any { it === avro4kNode }) return
        seenWith += avro4kNode
        pairs += apacheNode to avro4kNode
        apacheNode.type.name shouldBe avro4kNode.type.name
        when (avro4kNode) {
            is AvroSchema.RecordSchema -> avro4kNode.fields.forEachIndexed { i, field -> walk(apacheNode.fields[i].schema(), field.schema) }
            is AvroSchema.UnionSchema -> avro4kNode.types.forEachIndexed { i, type -> walk(apacheNode.types[i], type) }
            is AvroSchema.ArraySchema -> walk(apacheNode.elementType, avro4kNode.elementSchema)
            is AvroSchema.MapSchema -> walk(apacheNode.valueType, avro4kNode.valueSchema)
            else -> {}
        }
    }
    walk(apache, avro4k)
    return pairs
}

private fun <T : Any> List<T>.distinctByIdentity(): List<T> = IdentityHashMap<T, Unit>().also { map -> forEach { map[it] = Unit } }.keys.toList()

/**
 * A record referencing itself (directly, through a union, and as map values) and a named type used three times. It has 9
 * distinct nodes on each side: Root, Leaf, Leaf's int, the two unions, the array, the map, and the two nulls.
 */
private fun recursiveJson(namespace: String): String =
    """
    {"type":"record","name":"Root","namespace":"identity.$namespace","fields":[
      {"name":"left","type":{"type":"record","name":"Leaf","fields":[{"name":"v","type":"int"}]}},
      {"name":"right","type":"Leaf"},
      {"name":"self","type":["null","Root"]},
      {"name":"leaves","type":{"type":"array","items":"Leaf"}},
      {"name":"byName","type":{"type":"map","values":["null","Root"]}}
    ]}
    """.trimIndent()

private fun AvroSchema.RecordSchema.shouldShareLikeTheRecursiveSchema() {
    val leaf = getFieldByName("left").schema
    getFieldByName("right").schema shouldBeSameInstanceAs leaf
    (getFieldByName("leaves").schema as AvroSchema.ArraySchema).elementSchema shouldBeSameInstanceAs leaf
    (getFieldByName("self").schema as AvroSchema.UnionSchema).types[1] shouldBeSameInstanceAs this
}

// The helpers below are plain functions, so that the schemas they create are only referenced from their own frame (a
// suspending test body may keep its locals in its continuation).

private fun <T : Any> weakly(create: () -> T): WeakReference<T> = WeakReference(create())

/** An avro4k schema converted from an apache schema that is no longer referenced. */
private fun avro4kOfForgottenApache(namespace: String): Pair<AvroSchema, WeakReference<Schema>> {
    val apache = Schema.Parser().parse(recursiveJson(namespace))
    return apache.toAvro4k() to WeakReference(apache)
}

/** An apache schema converted from an avro4k schema that is no longer referenced. */
private fun apacheOfForgottenAvro4k(namespace: String): Pair<Schema, WeakReference<AvroSchema>> {
    val avro4k = AvroSchema.fromJsonString(recursiveJson(namespace))
    return avro4k.toApacheSchema() to WeakReference(avro4k)
}

private fun forgottenPairFromApache(namespace: String): Array<WeakReference<*>> {
    val apache = Schema.Parser().parse(recursiveJson(namespace))
    val avro4k = apache.toAvro4k() as AvroSchema.RecordSchema
    return arrayOf(WeakReference(apache), WeakReference(avro4k), WeakReference(apache.getField("left").schema()), WeakReference(avro4k.getFieldByName("left").schema))
}

private fun forgottenPairFromAvro4k(namespace: String): Array<WeakReference<*>> {
    val avro4k = AvroSchema.fromJsonString(recursiveJson(namespace)) as AvroSchema.RecordSchema
    val apache = avro4k.toApacheSchema()
    return arrayOf(WeakReference(apache), WeakReference(avro4k), WeakReference(apache.getField("left").schema()), WeakReference(avro4k.getFieldByName("left").schema))
}

/**
 * Collects and churns the caches until every reference is cleared, with a bounded number of attempts. The churn matters:
 * an entry whose key was collected keeps its value until the table is next rebuilt (WeakIdentityKeyCache's deferred
 * reclamation), and the partner of a pair is that value.
 */
private fun awaitCollected(vararg references: WeakReference<*>): Boolean {
    val sizeLimit = churnSizeLimit
    repeat(10) {
        if (references.all { it.get() == null }) return true
        if (!churnCaches(1, sizeLimit)) return false
    }
    return references.all { it.get() == null }
}

/**
 * Bounds every churn. If the caches retained what they should not, the churn's own entries would never be collected
 * either and each round would grow the tables — quadratically, as a put is O(capacity): without a bound, a leak shows up
 * as a test that never ends instead of one that fails. Fixed once, at the first churn: a limit relative to the current
 * size would compound from one test to the next under a leak.
 */
private val churnSizeLimit: Int by lazy { apacheConversionCacheSize() * 4 + 10_000 }

private val churnCounter = AtomicInteger()

/**
 * Converts enough throw-away schemas, both ways, to rebuild both tables at least [rebuilds] times, collecting before (so
 * that the rebuilds find the stale entries) and regularly during the churn (so that its own entries do not grow the tables).
 * Each iteration inserts two entries in each table, and a table rebuilds at the latest once its capacity is used, which is
 * less than 3 times its entries.
 *
 * @return false if the caches grew beyond [sizeLimit] entries, which means their entries are not collectable
 */
private fun churnCaches(
    rebuilds: Int,
    sizeLimit: Int = churnSizeLimit,
): Boolean {
    repeat(rebuilds) {
        System.gc()
        val iterations = apacheConversionCacheSize() * 3 / 2 + 100
        for (i in 0 until iterations) {
            Schema.create(Schema.Type.INT).toAvro4k()
            AvroSchema.IntSchema(mapOf("churn" to JsonPrimitive(churnCounter.incrementAndGet()))).toApacheSchema()
            if (i % 1_000 == 999) {
                System.gc()
                if (apacheConversionCacheSize() > sizeLimit) return false
            }
        }
    }
    return true
}