package com.github.avrokotlin.avro4k.internal.schema

import com.github.avrokotlin.avro4k.Avro
import com.github.avrokotlin.avro4k.AvroDecimal
import com.github.avrokotlin.avro4k.AvroSchema
import com.github.avrokotlin.avro4k.AvroSchema.RecordSchema
import com.github.avrokotlin.avro4k.AvroSchema.Type
import com.github.avrokotlin.avro4k.apacheSchema
import com.github.avrokotlin.avro4k.internal.codec.KotlinxIoDecoder
import com.github.avrokotlin.avro4k.toAvro4k
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.ints.shouldBeGreaterThan
import io.kotest.matchers.shouldBe
import kotlinx.io.Buffer
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import org.apache.avro.AvroRuntimeException
import org.apache.avro.Schema
import org.apache.avro.generic.GenericData
import org.apache.avro.generic.GenericDatumWriter
import org.apache.avro.io.EncoderFactory
import java.io.ByteArrayOutputStream
import java.io.File
import java.math.BigDecimal
import java.nio.ByteBuffer
import java.time.Instant
import java.time.LocalDate
import java.util.Collections
import java.util.IdentityHashMap
import java.util.UUID

/**
 * M3-07: the `AvroSchema` helpers answer exactly what the Apache-typed helpers answer, for every sub-schema of the
 * `jvmTest` resource corpus, of schemas generated by avro4k (logical types, nullable unions), and of hand-written
 * Apache schemas (aliases, unions of every type). Each Apache schema is converted with apache-interop's `toAvro4k()`,
 * then both trees are walked in parallel.
 *
 * The reference is a **frozen copy** of the Apache-typed helpers (bottom of this file, copied from `c3149f0`), not
 * core's own: M3-11 retypes those, and M3-01's rule keeps tests off core's Apache-typed internals.
 */
internal class AvroSchemaHelpersDifferentialTest : StringSpec({
    val corpus: List<Pair<String, Schema>> by lazy {
        val dir = File(AvroSchemaHelpersDifferentialTest::class.java.getResource("/basic.json")!!.toURI()).parentFile
        val resources =
            dir.listFiles { f -> f.name.endsWith(".json") }!!.sortedBy { it.name }.map { it.name to Schema.Parser().parse(it) }
        val generated =
            listOf(
                "generated LogicalTypes" to Avro.apacheSchema(LogicalTypes.serializer()),
                "generated NullableLogicalTypes" to Avro.apacheSchema(NullableLogicalTypes.serializer())
            )
        val handWritten = HAND_WRITTEN.mapIndexed { i, json -> "hand-written #$i" to Schema.Parser().parse(json) }
        resources + generated + handWritten
    }

    "the corpus is large enough to mean something" {
        var unions = 0
        var named = 0
        var logical = 0
        corpus.forEach { (_, schema) ->
            walk(schema, schema.toAvro4k()) { apache, _ ->
                if (apache.isUnion) unions++
                if (apache.isNamedSchemaRef()) named++
                if (apache.logicalType != null) logical++
            }
        }
        corpus.size shouldBeGreaterThan 55
        unions shouldBeGreaterThan 30
        named shouldBeGreaterThan 60
        logical shouldBeGreaterThan 10
    }

    "kinds, names and aliases match the Apache helpers" {
        corpus.forEach { (name, schema) ->
            walk(schema, schema.toAvro4k()) { apache, model ->
                withClue("$name: $apache") {
                    model.isUnion shouldBe apache.isUnion
                    model.type.getName() shouldBe apache.type.getName()
                    model.fullNameForMessages shouldBe apache.fullName
                    // the model names a union `union`, Apache `union[<branches' simple names>]`
                    model.fullName shouldBe if (apache.isUnion) "union" else apache.fullName
                    model.isNamedSchema() shouldBe apache.isNamedSchemaRef()
                    model.nonFailingAliases() shouldBe apache.nonFailingAliasesRef()
                    model.isNonNullScalarType() shouldBe apache.isNonNullScalarTypeRef()

                    val candidates = listOf(model.fullName, apache.fullName, apache.name, "nope", "int", "union") + apache.nonFailingAliasesRef()
                    // on a union, the match follows each side's full name (see above): no call site matches a union's name
                    if (!apache.isUnion) {
                        candidates.forEach { candidate ->
                            model.isFullNameMatch(candidate) shouldBe apache.isFullNameMatchRef(candidate)
                            model.isFullNameOrAliasMatch("nope") { setOf(candidate) } shouldBe apache.isFullNameOrAliasMatchRef("nope") { setOf(candidate) }
                        }
                    }
                }
            }
        }
    }

    "the Apache-shaped accessors return the same values, or fail with the same exception class and message" {
        val accessors: List<Pair<(Schema) -> Any?, (AvroSchema) -> Any?>> =
            listOf(
                { s: Schema -> s.types.map { it.fullName } } to { s: AvroSchema -> s.types.map { it.fullName } },
                { s: Schema -> s.fixedSize } to { s: AvroSchema -> s.fixedSize },
                { s: Schema -> s.enumSymbols } to { s: AvroSchema -> s.enumSymbols },
                { s: Schema -> s.elementType.fullName } to { s: AvroSchema -> s.elementType.fullNameForMessages },
                { s: Schema -> s.valueType.fullName } to { s: AvroSchema -> s.valueType.fullNameForMessages },
                { s: Schema -> s.fields.map { it.name() } } to { s: AvroSchema -> s.fields.map { it.name } },
                { s: Schema -> s.aliases } to { s: AvroSchema -> s.aliases },
                { s: Schema -> s.hasEnumSymbol("A") } to { s: AvroSchema -> s.hasEnumSymbol("A") }
            )
        var failures = 0
        corpus.forEach { (name, schema) ->
            walk(schema, schema.toAvro4k()) { apache, model ->
                accessors.forEachIndexed { index, (apacheAccessor, modelAccessor) ->
                    withClue("$name, accessor #$index: $apache") {
                        val expected = runCatching { apacheAccessor(apache) }
                        val actual = runCatching { modelAccessor(model) }
                        actual.isSuccess shouldBe expected.isSuccess
                        if (expected.isSuccess) {
                            actual.getOrNull() shouldBe expected.getOrNull()
                        } else {
                            failures++
                            val apacheError = expected.exceptionOrNull()!!
                            val modelError = actual.exceptionOrNull()!!
                            apacheError::class shouldBe AvroRuntimeException::class
                            modelError::class shouldBe RuntimeException::class
                            // "Not a union: " etc.; the JSON after it is compared for unnamed schemas, whose rendering is
                            // canonical (a named schema's key order is the JSON serializer's own)
                            modelError.message!!.substringBefore(": ") shouldBe apacheError.message!!.substringBefore(": ")
                            if (!apache.isNamedSchemaRef() && !apache.containsNamedSchema()) {
                                modelError.message shouldBe apacheError.message
                            }
                        }
                    }
                }
            }
        }
        failures shouldBeGreaterThan 1000
    }

    "enum ordinals match" {
        corpus.forEach { (name, schema) ->
            walk(schema, schema.toAvro4k()) { apache, model ->
                if (apache.type == Schema.Type.ENUM) {
                    withClue("$name: $apache") {
                        apache.enumSymbols.forEach { symbol ->
                            model.getEnumOrdinal(symbol) shouldBe apache.getEnumOrdinal(symbol)
                            model.hasEnumSymbol(symbol) shouldBe true
                        }
                        model.hasEnumSymbol("not-a-symbol") shouldBe apache.hasEnumSymbol("not-a-symbol")
                    }
                }
            }
        }
    }

    "union branch lookups match" {
        val unnamedTypes = Schema.Type.entries.filter { it !in setOf(Schema.Type.RECORD, Schema.Type.ENUM, Schema.Type.FIXED, Schema.Type.UNION) }
        var lookups = 0
        corpus.forEach { (name, schema) ->
            walk(schema, schema.toAvro4k()) { apache, model ->
                if (!apache.isUnion) return@walk
                withClue("$name: $apache") {
                    unnamedTypes.forEach { type ->
                        model.getIndexTyped(type.toModel()) shouldBe (apache.getIndexTypedRef(type) ?: -1)
                        lookups++
                    }
                    // named types: the first branch of that type (Apache's name lookup is not a type lookup, see KDoc)
                    listOf(Schema.Type.RECORD, Schema.Type.ENUM, Schema.Type.FIXED).forEach { type ->
                        model.getIndexTyped(type.toModel()) shouldBe apache.types.indexOfFirst { it.type == type }
                    }

                    val logicalNames = apache.types.mapNotNull { it.logicalType?.name } + listOf("nope", "uuid", "date")
                    val types = Schema.Type.entries.filter { it != Schema.Type.UNION }
                    logicalNames.forEach { logicalName ->
                        types.forEach { first ->
                            model.getIndexLogicallyTyped(logicalName, first.toModel()) shouldBe
                                (apache.getIndexLogicallyTypedRef(logicalName, first) ?: -1)
                            types.forEach { second ->
                                model.getIndexLogicallyTyped(logicalName, first.toModel(), second.toModel()) shouldBe
                                    (apache.getIndexLogicallyTypedRef(logicalName, first, second) ?: -1)
                            }
                            lookups++
                        }
                    }

                    val names = apache.types.flatMap { listOf(it.fullName) + it.nonFailingAliasesRef() } + listOf("nope", "com.nope.Nope")
                    names.forEach { expectedName ->
                        model.getIndexNamedOrAliased(expectedName) shouldBe apache.getIndexNamedOrAliasedRef(expectedName)
                        lookups++
                    }
                }
            }
        }
        lookups shouldBeGreaterThan 1000
    }

    "union shaping matches" {
        corpus.forEach { (name, schema) ->
            walk(schema, schema.toAvro4k()) { apache, model ->
                withClue("$name: $apache") {
                    model.asSchemaList().map { it.fullName } shouldBe apache.asSchemaListRef().map { it.fullName }
                    for (index in 0..apache.asSchemaListRef().size) {
                        model.moveToHeadOfUnion(index).branchNames() shouldBe apache.moveToHeadOfUnionRef(index).branchNames()
                        model.moveToTailOfUnion(index).branchNames() shouldBe apache.moveToTailOfUnionRef(index).branchNames()
                    }
                    Schema.Type.entries.forEach { type ->
                        model.moveToHeadOfUnion { it.type === type.toModel() }.branchNames() shouldBe
                            apache.moveToHeadOfUnionRef { it.type === type }.branchNames()
                        model.moveToTailOfUnion { it.type === type.toModel() }.branchNames() shouldBe
                            apache.moveToTailOfUnionRef { it.type === type }.branchNames()
                    }
                }
            }
        }
    }

    "documented difference: a logical type Apache ignores (invalid here) is still matched by name" {
        // Apache's getLogicalType() drops a `date` on a string (validation fails); logicalTypeName is the raw prop
        val apache = Schema.Parser().parse("""["null",{"type":"string","logicalType":"date"}]""")
        apache.types[1].logicalType shouldBe null
        apache.getIndexLogicallyTypedRef("date", Schema.Type.STRING) shouldBe null
        apache.toAvro4k().getIndexLogicallyTyped("date", Type.STRING) shouldBe 1
    }

    "documented difference: a union's full name, and so isFullNameMatch on a union" {
        val apache = Schema.Parser().parse("""["null",{"type":"record","name":"R","namespace":"com.a","fields":[]},{"type":"array","items":"int"}]""")
        val model = apache.toAvro4k()
        apache.fullName shouldBe "union[null, R, array]"
        model.fullNameForMessages shouldBe "union[null, R, array]"
        model.fullName shouldBe "union"
        apache.isFullNameMatchRef("union") shouldBe false
        model.isFullNameMatch("union") shouldBe true
        apache.isFullNameMatchRef("union[null, R, array]") shouldBe true
        model.isFullNameMatch("union[null, R, array]") shouldBe false
    }

    "documented difference: getIndexTyped of a named type is a type lookup, not Apache's name lookup" {
        val apache = Schema.Parser().parse("""[{"type":"record","name":"A","fields":[]},{"type":"record","name":"record","fields":[]}]""")
        apache.getIndexTypedRef(Schema.Type.RECORD) shouldBe 1
        apache.toAvro4k().getIndexTyped(Type.RECORD) shouldBe 0
    }

    "skip consumes exactly what Apache's encoders write, single-block and split into byte-sized blocks" {
        val schema = Schema.Parser().parse(SKIP_SCHEMA)
        val record = bigRecord(schema)
        val model = schema.toAvro4k()

        val direct = ByteArrayOutputStream()
        EncoderFactory.get().binaryEncoder(direct, null).also { GenericDatumWriter<Any>(schema).write(record, it) }.flush()
        // a small block size forces many blocks, each written as a negative count followed by its byte size
        val blocking = ByteArrayOutputStream()
        EncoderFactory().configureBlockSize(64).blockingBinaryEncoder(blocking, null)
            .also { GenericDatumWriter<Any>(schema).write(record, it) }.flush()
        blocking.size() shouldBeGreaterThan direct.size()

        listOf(direct.toByteArray(), blocking.toByteArray()).forEach { bytes ->
            // twice in a row, to also check that the first skip stops exactly at the end of the first value
            val buffer = Buffer().apply { write(bytes + bytes) }
            val decoder = KotlinxIoDecoder(buffer)
            decoder.skip(model)
            buffer.size shouldBe bytes.size.toLong()
            decoder.skip(model)
            buffer.exhausted() shouldBe true
        }
    }
}) {
    @Serializable
    private data class LogicalTypes(
        @Contextual val uuid: UUID,
        @Contextual val instant: Instant,
        @Contextual val date: LocalDate,
        @Contextual @AvroDecimal(scale = 2, precision = 8) val decimal: BigDecimal,
        val char: Char,
    )

    @Serializable
    private data class NullableLogicalTypes(
        @Contextual val uuid: UUID?,
        @Contextual val instant: Instant?,
        @Contextual val date: LocalDate?,
        @Contextual @AvroDecimal(scale = 2, precision = 8) val decimal: BigDecimal?,
        val char: Char?,
        val nested: LogicalTypes?,
        val list: List<LogicalTypes?>?,
    )
}

// ---- the walk ----

private fun walk(
    apache: Schema,
    model: AvroSchema,
    seen: MutableSet<Schema> = Collections.newSetFromMap(IdentityHashMap()),
    visit: (Schema, AvroSchema) -> Unit,
) {
    visit(apache, model)
    when (apache.type!!) {
        Schema.Type.UNION -> apache.types.forEachIndexed { i, branch -> walk(branch, model.types[i], seen, visit) }

        Schema.Type.ARRAY -> walk(apache.elementType, model.elementType, seen, visit)

        Schema.Type.MAP -> walk(apache.valueType, model.valueType, seen, visit)

        Schema.Type.RECORD -> {
            if (!seen.add(apache)) return
            apache.fields.forEachIndexed { i, field -> walk(field.schema(), (model as RecordSchema).fields[i].schema, seen, visit) }
        }

        else -> {}
    }
}

private fun Schema.Type.toModel(): Type = Type.valueOf(name)

private fun Schema.containsNamedSchema(): Boolean =
    when (type!!) {
        Schema.Type.UNION -> types.any { it.isNamedSchemaRef() || it.containsNamedSchema() }
        Schema.Type.ARRAY -> elementType.let { it.isNamedSchemaRef() || it.containsNamedSchema() }
        Schema.Type.MAP -> valueType.let { it.isNamedSchemaRef() || it.containsNamedSchema() }
        else -> false
    }

private fun AvroSchema.branchNames(): Any = if (isUnion) types.map { it.fullName } else fullName

private fun Schema.branchNames(): Any = if (isUnion) types.map { it.fullName } else fullName

// ---- the frozen reference: the Apache-typed helpers at c3149f0, verbatim except for the `Ref` suffix ----

// core/src/jvmMain/.../internal/helpers.kt
private fun Schema.asSchemaListRef(): List<Schema> {
    if (!isUnion) return listOf(this)
    return types
}

private fun Schema.isNamedSchemaRef(): Boolean {
    return when (this.type) {
        Schema.Type.RECORD, Schema.Type.ENUM, Schema.Type.FIXED -> true
        else -> false
    }
}

private fun Schema.nonFailingAliasesRef(): Set<String> {
    return if (isNamedSchemaRef()) {
        aliases
    } else {
        emptySet()
    }
}

private fun Schema.isFullNameOrAliasMatchRef(
    fullName: String,
    aliases: () -> Set<String>,
): Boolean {
    return isFullNameMatchRef(fullName) || aliases().any { isFullNameMatchRef(it) }
}

private fun Schema.isFullNameMatchRef(fullNameToMatch: String): Boolean {
    return fullName == fullNameToMatch || (isNamedSchemaRef() && aliases.any { it == fullNameToMatch })
}

// core/src/jvmMain/.../AvroEncoder.kt
private fun Schema.getIndexLogicallyTypedRef(
    logicalTypeName: String,
    vararg oneOf: Schema.Type,
): Int? {
    return oneOf.firstNotNullOfOrNull { expectedType ->
        when (expectedType) {
            Schema.Type.FIXED, Schema.Type.RECORD, Schema.Type.ENUM -> types.indexOfFirst { it.type == expectedType && it.logicalType?.name == logicalTypeName }.takeIf { it >= 0 }
            else -> getIndexNamed(expectedType.getName())?.takeIf { types[it].logicalType?.name == logicalTypeName }
        }
    }
}

private fun Schema.getIndexNamedOrAliasedRef(expectedName: String): Int? {
    return getIndexNamed(expectedName)
        ?: types.indexOfFirst { it.isNamedSchemaRef() && it.aliases.contains(expectedName) }.takeIf { it >= 0 }
}

private fun Schema.getIndexTypedRef(expectedType: Schema.Type): Int? {
    @Suppress("UsePropertyAccessSyntax")
    return getIndexNamed(expectedType.getName())
}

// core/src/jvmMain/.../internal/schema/ClassVisitor.kt
private fun Schema.moveToHeadOfUnionRef(predicate: (Schema) -> Boolean): Schema {
    if (!isUnion) {
        return this
    }
    types.indexOfFirst(predicate).let { index ->
        if (index == -1) {
            return this
        }
        return moveToHeadOfUnionRef(index)
    }
}

private fun Schema.moveToHeadOfUnionRef(typeIndex: Int): Schema {
    if (!isUnion || typeIndex >= types.size) {
        return this
    }
    return Schema.createUnion(types.toMutableList().apply { add(0, removeAt(typeIndex)) })
}

private fun Schema.moveToTailOfUnionRef(predicate: (Schema) -> Boolean): Schema {
    if (!isUnion) {
        return this
    }
    types.indexOfFirst(predicate).let { index ->
        if (index == -1) {
            return this
        }
        return moveToTailOfUnionRef(index)
    }
}

private fun Schema.moveToTailOfUnionRef(typeIndex: Int): Schema {
    if (!isUnion || typeIndex >= types.size) {
        return this
    }
    return Schema.createUnion(types.toMutableList().apply { add(removeAt(typeIndex)) })
}

// core/src/jvmMain/.../internal/schema/MapVisitor.kt
private fun Schema.isNonNullScalarTypeRef(): Boolean =
    when (type) {
        Schema.Type.BOOLEAN,
        Schema.Type.INT,
        Schema.Type.LONG,
        Schema.Type.FLOAT,
        Schema.Type.DOUBLE,
        Schema.Type.STRING,
        Schema.Type.ENUM,
        Schema.Type.BYTES,
        Schema.Type.FIXED,
        -> true

        Schema.Type.NULL,
        Schema.Type.ARRAY,
        Schema.Type.MAP,
        Schema.Type.RECORD,
        null,
        -> false

        Schema.Type.UNION -> types.all { it.isNonNullScalarTypeRef() }
    }

// ---- fixtures ----

private val HAND_WRITTEN =
    listOf(
        // a union of every unnamed type, then named types with aliases
        """
        ["null","boolean","int","long","float","double","bytes","string",{"type":"array","items":"int"},{"type":"map","values":"string"},
         {"type":"record","name":"R","namespace":"com.a","aliases":["com.b.OldR","Other"],"fields":[{"name":"x","type":"int"}]},
         {"type":"enum","name":"E","namespace":"com.a","aliases":["OldE"],"symbols":["A","B","C"]},
         {"type":"fixed","name":"F","namespace":"com.a","aliases":["com.c.OldF"],"size":4}]
        """,
        // logical types in unions, including two branches with the same logical type on different types
        """
        {"type":"record","name":"L","fields":[
          {"name":"a","type":["null",{"type":"int","logicalType":"date"},{"type":"long","logicalType":"timestamp-millis"},{"type":"string","logicalType":"uuid"}]},
          {"name":"b","type":[{"type":"fixed","name":"D","size":8,"logicalType":"decimal","precision":10,"scale":2},{"type":"bytes","logicalType":"decimal","precision":10,"scale":2}]},
          {"name":"c","type":[{"type":"bytes","logicalType":"decimal","precision":5},{"type":"fixed","name":"Dur","size":12,"logicalType":"duration"},"string"]},
          {"name":"d","type":{"type":"map","values":["null",{"type":"long","logicalType":"time-micros"},{"type":"enum","name":"E2","symbols":["X"]}]}}
        ]}
        """,
        // unions whose non-null branch is a map, an array, or a record, with the null branch in different positions
        """
        {"type":"record","name":"U","namespace":"u","fields":[
          {"name":"a","type":[{"type":"array","items":"long"},"null"]},
          {"name":"b","type":["null",{"type":"map","values":{"type":"array","items":"string"}}]},
          {"name":"c","type":[{"type":"record","name":"In","aliases":["u.OldIn"],"fields":[{"name":"z","type":["null","In"]}]},"null","string"]},
          {"name":"e","type":{"type":"enum","name":"Big","symbols":["A","B","C","D","E","F","G","H"],"default":"C"}}
        ]}
        """
    )

private val SKIP_SCHEMA =
    """
    {"type":"record","name":"Big","namespace":"diff","fields":[
      {"name":"i","type":"int"},
      {"name":"s","type":"string"},
      {"name":"u","type":["null","long","string"]},
      {"name":"e","type":{"type":"enum","name":"E","symbols":["A","B","C"]}},
      {"name":"f","type":{"type":"fixed","name":"F","size":3}},
      {"name":"b","type":"bytes"},
      {"name":"arr","type":{"type":"array","items":{"type":"record","name":"Item","fields":[
        {"name":"x","type":"int"},
        {"name":"tags","type":{"type":"array","items":"string"}},
        {"name":"next","type":["null","Item"]}
      ]}}},
      {"name":"m","type":{"type":"map","values":{"type":"array","items":"long"}}},
      {"name":"d","type":"double"},
      {"name":"fl","type":"float"},
      {"name":"bo","type":"boolean"},
      {"name":"n","type":"null"}
    ]}
    """

private fun bigRecord(schema: Schema): GenericData.Record {
    val itemSchema = schema.getField("arr").schema().elementType

    fun item(x: Int, next: GenericData.Record?) =
        GenericData.Record(itemSchema).apply {
            put("x", x)
            put("tags", List(x % 4) { "tag-$x-$it" })
            put("next", next)
        }
    return GenericData.Record(schema).apply {
        put("i", 42)
        put("s", "hello")
        put("u", "a string branch")
        put("e", GenericData.EnumSymbol(schema.getField("e").schema(), "B"))
        put("f", GenericData.Fixed(schema.getField("f").schema(), byteArrayOf(1, 2, 3)))
        put("b", ByteBuffer.wrap(ByteArray(100) { it.toByte() }))
        put("arr", List(60) { item(it, if (it % 3 == 0) item(it + 1000, null) else null) })
        put("m", (0 until 25).associate { "key-$it" to List(it % 7) { n -> n * 1_000_000_007L } })
        put("d", 1.5)
        put("fl", 2.5f)
        put("bo", true)
        put("n", null)
    }
}